from enum import StrEnum


class Severity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class PolicyMode(StrEnum):
    DIAGNOSTIC_ONLY = "DIAGNOSTIC_ONLY"
    ADVISORY = "ADVISORY"
    MANUAL_APPROVAL = "MANUAL_APPROVAL"


class RunbookStepType(StrEnum):
    HTTP_CHECK = "HTTP_CHECK"
    METRIC_QUERY = "METRIC_QUERY"
    PULSEWATCH_LOOKUP = "PULSEWATCH_LOOKUP"
    STATIC_HINT = "STATIC_HINT"
    DEPENDENCY_HEALTH = "DEPENDENCY_HEALTH"
    MANUAL_CHECK = "MANUAL_CHECK"
    REMEDIATION_PREVIEW = "REMEDIATION_PREVIEW"


class ExecutionStatus(StrEnum):
    RUNNING = "RUNNING"
    WAITING_FOR_OPERATOR = "WAITING_FOR_OPERATOR"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    REUSED = "REUSED"
    SUPPRESSED = "SUPPRESSED"
    SKIPPED = "SKIPPED"


class StepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    WAITING_FOR_OPERATOR = "WAITING_FOR_OPERATOR"


class FeedbackRating(StrEnum):
    HELPFUL = "HELPFUL"
    NOT_HELPFUL = "NOT_HELPFUL"
    WRONG_RUNBOOK = "WRONG_RUNBOOK"
    NEEDS_MORE_CONTEXT = "NEEDS_MORE_CONTEXT"


class DependencyType(StrEnum):
    DATABASE = "DATABASE"
    CACHE = "CACHE"
    INTERNAL_SERVICE = "INTERNAL_SERVICE"
    EXTERNAL_PROVIDER = "EXTERNAL_PROVIDER"


class DependencyCriticality(StrEnum):
    REQUIRED = "REQUIRED"
    DEGRADED_OK = "DEGRADED_OK"
    OPTIONAL = "OPTIONAL"
